docs_dir: ./doc
extra_css: ['https://media.readthedocs.org/css/badge_only.css', 'https://media.readthedocs.org/css/readthedocs-doc-embed.css']
extra_javascript: [readthedocs-data.js, 'https://media.readthedocs.org/static/core/js/readthedocs-doc-embed.js',
  'https://media.readthedocs.org/javascript/readthedocs-analytics.js']
google_analytics: null
site_name: cosmo-model-training
pages:
- Index: 'index.md'
- Components of the COSMO software and external prerequisites: 'components.md'
- Building prerequisites: 'building_prerequisites.md'
- Building COSMO code: 'building_cosmo_code.md'
- COSMO data formats: 'cosmo_data_formats.md'
- Main ingredients for running the COSMO model: 'main_ingredients.md'
- Input constant data: 'input_constant_data.md'
- Input model initial and boundary conditions: 'input_ic_bc.md'
- COSMO constant data: 'cosmo_constant_data.md'
- Retrieving ECMWF reanalysis: 'retrieving_ecmwf_reanalysis.md'
- Preparing the environment for grib_api: 'preparing_for_grib_api.md'
- Running Int2lm: 'running_int2lm.md'
- Running Cosmo: 'running_cosmo.md'
- Installing grads: 'installing_grads.md'
- Installing postprocessing software: 'installing_postprocessing_software.md'
- Importing Cosmo data in grads: 'cosmo_in_grads.md'
- Other useful pre- and post-processing operations: 'other_pre_and_post_proc.md'
- Rotated grid: 'rotated_grid.md'
